import {
  getUploads,
  updateFollower,
  getPublicUploads,
  getPublicProfile,
  getPublicPlaylist,
  getRecommendedByProfile,
  getAutoGeneratedPlaylist,
  getFollowersProfile,
  getFollowingsProfile,
  getFollowersProfilePublic,
  getPlaylistAudios,
  getPrivatePlaylistAudios,
  getIsFollowing
} from "@/controllers/profile"
import { isAuth, profileAuth } from "@/middlewares/auth"
import { Router } from "express"

const router = Router()

router.post("/update-follower/:profileId", isAuth, updateFollower)
router.get("/uploads", isAuth, getUploads)
router.get("/uploads/:profileId", getPublicUploads)
router.get("/info/:profileId", getPublicProfile)
router.get("/info/:profileId", getPublicProfile)
router.get("/playlist/:profileId", getPublicPlaylist)
router.get("/recommended", profileAuth, getRecommendedByProfile)
router.get("/auto-generated-playlist", isAuth, getAutoGeneratedPlaylist)
router.get("/followers", isAuth, getFollowersProfile)
router.get("/followers/:profileId", isAuth, getFollowersProfilePublic)
router.get("/followings", isAuth, getFollowingsProfile)
router.get("/followings", isAuth, getFollowingsProfile)
router.get("/playlist-audios/:playlistId", isAuth, getPlaylistAudios)
router.get("/private-playlist-audios/:playlistId", isAuth, getPrivatePlaylistAudios)
router.get("/is-following/:profileId", isAuth, getIsFollowing)

export default router
